name: todo_app
description: A Todo app with Pomodoro timer
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true 